spring.application.name=FileSharingApp
server.port=9090

spring.datasource.url=jdbc:mysql://localhost:3306/cw_files_prj
spring.datasource.username=root
spring.datasource.password=R@mbharat123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.security.user.password=1111



 logging.level.org.springframework.web=DEBUG

spring.security.oauth2.client.registration.google.client-id=${googleID}
 spring.security.oauth2.client.registration.google.client-secret=${googleSecret}

 spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:9090/login/oauth2/code/google

 spring.security.oauth2.client.registration.github.client-id=${gitHubID}
 spring.security.oauth2.client.registration.github.client-secret=${gitHubSecret}